"""migration

Revision ID: 9030f7b609ae
Revises: 00cb20a425f8
Create Date: 2023-01-13 10:31:16.263406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9030f7b609ae'
down_revision = '00cb20a425f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
