"""migration

Revision ID: dfae3547cf48
Revises: 04e51135c7b9
Create Date: 2023-02-01 11:41:10.998131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfae3547cf48'
down_revision = '04e51135c7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
